version: '3.9'

services:

  readingisgood-service:
    container_name: readingisgood-service
    image: readingisgood-service:latest
    build:
      context: readingisgood
      dockerfile: Dockerfile
    environment:
      RDS_HOSTNAME: $RDS_HOSTNAME
      RDS_PORT: $RDS_PORT
      RDS_DB_NAME: $RDS_DB_NAME
      RDS_USERNAME: $RDS_USERNAME
      RDS_PASSWORD: $RDS_PASSWORD
    ports:
      - "${SERVICE_EXPOSED_PORT}:8080"
    restart: always
    depends_on:
      - readingisgood-database

  readingisgood-database:
    container_name: readingisgood-database
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: $RDS_PASSWORD
      MYSQL_DATABASE: $RDS_DB_NAME
    ports:
      - "${RDS_EXPOSED_PORT}:3306"
    restart: always
    volumes:
      - ./volumes:/var/lib/mysql

