DELETE FROM AUTHORITY;
DELETE FROM USER;

INSERT INTO USER(EMAIL, PASSWORD) VALUES('testuser1@getir.com', '$2a$10$UuLEbfTsDQ2YRZoOe9UdduYN7ST8/F9Ae3qWpCGcON7yyToYGprmO');
INSERT INTO USER(EMAIL, PASSWORD) VALUES('testuser2@getir.com', '$2a$10$hOIEowEERTF8ok6D1gzDr.0926NGOTQfoYMf9fPF1h/hPM7LFHoyi');
INSERT INTO USER(EMAIL, PASSWORD) VALUES('testuser3@getir.com', '$2a$10$/SELnL66ikXWavNR3EXR7uhVkXOoKUt3g26U/Sl30BgZ5gdC1V0U6');
INSERT INTO USER(EMAIL, PASSWORD) VALUES('testuser4@getir.com', '$2a$10$j4KfXKjbZcbA8HWiRugUPOADttqafK6s5oxALKnZqiljYCTgYJSYi');
INSERT INTO USER(EMAIL, PASSWORD) VALUES('testuser5@getir.com', '$2a$10$ZVi3fklr3GSzSHtu4Yh5U.BXWoM0sbn.KNHxJ.Ic36CQ5nZA.WQiq');

INSERT INTO AUTHORITY(USERNAME, ROLE) VALUES('testuser1@getir.com', 'CUSTOMER');
INSERT INTO AUTHORITY(USERNAME, ROLE) VALUES('testuser2@getir.com', 'CUSTOMER');
INSERT INTO AUTHORITY(USERNAME, ROLE) VALUES('testuser3@getir.com', 'CUSTOMER');
INSERT INTO AUTHORITY(USERNAME, ROLE) VALUES('testuser4@getir.com', 'CUSTOMER');
INSERT INTO AUTHORITY(USERNAME, ROLE) VALUES('testuser5@getir.com', 'CUSTOMER');