INSERT INTO USER(ID, EMAIL, PASSWORD) VALUES(2, 'testuser1@getir.com', '$2a$10$UuLEbfTsDQ2YRZoOe9UdduYN7ST8/F9Ae3qWpCGcON7yyToYGprmO');
INSERT INTO USER(ID, EMAIL, PASSWORD) VALUES(3, 'testuser2@getir.com', '$2a$10$hOIEowEERTF8ok6D1gzDr.0926NGOTQfoYMf9fPF1h/hPM7LFHoyi');
INSERT INTO USER(ID, EMAIL, PASSWORD) VALUES(4, 'testuser3@getir.com', '$2a$10$/SELnL66ikXWavNR3EXR7uhVkXOoKUt3g26U/Sl30BgZ5gdC1V0U6');
INSERT INTO USER(ID, EMAIL, PASSWORD) VALUES(5, 'testuser4@getir.com', '$2a$10$j4KfXKjbZcbA8HWiRugUPOADttqafK6s5oxALKnZqiljYCTgYJSYi');
INSERT INTO USER(ID, EMAIL, PASSWORD) VALUES(6, 'testuser5@getir.com', '$2a$10$ZVi3fklr3GSzSHtu4Yh5U.BXWoM0sbn.KNHxJ.Ic36CQ5nZA.WQiq');

INSERT INTO AUTHORITY(ID, USERNAME, ROLE) VALUES(2, 'testuser1@getir.com', 'CUSTOMER');
INSERT INTO AUTHORITY(ID, USERNAME, ROLE) VALUES(3, 'testuser2@getir.com', 'CUSTOMER');
INSERT INTO AUTHORITY(ID, USERNAME, ROLE) VALUES(4, 'testuser3@getir.com', 'CUSTOMER');
INSERT INTO AUTHORITY(ID, USERNAME, ROLE) VALUES(5, 'testuser4@getir.com', 'CUSTOMER');
INSERT INTO AUTHORITY(ID, USERNAME, ROLE) VALUES(6, 'testuser5@getir.com', 'CUSTOMER');